name: Docker Image Scan Demo2

on:
  push:
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4
        
    # Install & prepare Snyk
    - run: npm install --location=global snyk
    
    - run: snyk auth 43e8641d-b783-486d-b00a-fe4965e49507
    
    - name: Snyk Container Scanning
      run: snyk container monitor --org=miklos_org_1
      continue-on-error: true
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:8})
            
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcsnyk/juice-shop:latest,mcsnyk/juice-shop:${{steps.vars.outputs.tag}}
   
    - name: Snyk container scan with DockerMaster
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        DEBUG: true
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: mcsnyk/juice-shop:${{steps.vars.outputs.tag}}
        args: --file=Dockerfile  
        
