name: Prebuilt repo + Snyk Security Scanning (OS, Code, Docker, IaC)

# Runs 4 Snyk Products (Code, Open Source, Container, IaC)
# Snyk installation via npm
# Node.js version: 18.4
# Outputs the results to the pipeline and in SARIF-format to the security tab

# Prerequisites:
# - Set a SNYK_TOKEN and a SNYK_ORG in the pipelines secrets

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4

    # Install & prepare Snyk
    - run: npm install --location=global snyk snyk-to-html      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}
    
#     - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
#       run: |
#         docker build . -t storybooks:latest
#         snyk container monitor mcsnyk/storybooks:latest --org=3ee0d99d-1651-4b78-b9a4-a2658bd1815e

    
    - name: Snyk Open Source scanning
      run: snyk test --all-projects
      continue-on-error: true
    
    - name: Snyk Open Source generating HTML
      run: snyk test --all-projects --json | snyk-to-html>OS_results.html
      continue-on-error: true
      
    - name: Snyk Open Source generating SARIF
      run: snyk test --all-projects --sarif  > results_os.sarif
      continue-on-error: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: Snyk Report
          path: OS_results.html
          
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results_os.sarif

#     # Run Snyk Code
#     - name: Run Snyk Code
#       run: |
#          snyk code test --sarif  > results_code.sarif
#       continue-on-error: true
#     - name: Run snyk-to-html
#       run: |
#          snyk-to-html -i results_code.sarif -o results_code.html
#       continue-on-error: true
#     - name: Archive Snyk Scan Results
#       uses: actions/upload-artifact@v2
#       with:
#           name: Archive Snyk Code Scan Results
#           path: | 
#             results_code.sarif
#             results_code.html  
#     - name: Upload SARIF file
#       uses: github/codeql-action/upload-sarif@v2
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: results_code.sarif
        
