name: Prebuilt repo + Snyk Security Scanning (OS, Code, Docker, IaC)
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4

    # Install & prepare Snyk
    - run: npm install --location=global snyk snyk-to-html      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Run Snyk Code
#     - name: Run Snyk Code Scan
#       run: |
#          snyk code test --sarif  > results_code.sarif
#       continue-on-error: true
#     - name: Run snyk-to-html
#       run: |
#          snyk-to-html -i results_code.sarif -o results_code.html
#       continue-on-error: true
#     - name: Archive Snyk Scan Results
#       uses: actions/upload-artifact@v2
#       with:
#           name: Archive Snyk Code Scan Results
#           path: | 
#             results_code.sarif
#             results_code.html  
#     - name: Upload SARIF file
#       uses: github/codeql-action/upload-sarif@v2
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: results_code.sarif
    
    # Run Snyk Open Source
#     - name: Run Snyk Open Source Scan
#       run: |
#          snyk test --all-projects --sarif  > results_os.sarif
#       continue-on-error: true
#     - name: Run snyk-to-html
#       run: |
#          snyk-to-html -i results_os.sarif -o results_os.html
#       continue-on-error: true
#     - name: Archive Snyk Scan Results
#       uses: actions/upload-artifact@v2
#       with:
#           name: Archive Snyk Open Source Scan Results
#           path: | 
#             results_os.sarif
#             results_os.html  
#     - name: Upload SARIF file
#       uses: github/codeql-action/upload-sarif@v2
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: results_os.sarif
        
    # Run Snyk Container
    - name: Run Snyk Container Scan
      run: |
         docker build . -t juiceshop:latest
         snyk container test juiceshop:latest --file=Dockerfile --sarif  > results_container.sarif
      continue-on-error: true
    - name: Run snyk-to-html
      run: |
         snyk-to-html -i results_container.sarif -o results_container.html
      continue-on-error: true
    - name: Archive Snyk Scan Results
      uses: actions/upload-artifact@v2
      with:
          name: Archive Snyk Container Scan Results
          path: | 
            results_container.sarif
            results_container.html  
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results_container.sarif      

    # Run IaC Source
#     - name: Run Snyk IaC Scan
#       run: |
#          snyk iac test --sarif  > results_iac.sarif
#       continue-on-error: true
#     - name: Run snyk-to-html
#       run: |
#          snyk-to-html -i results_iac.sarif -o results_iac.html
#       continue-on-error: true
#     - name: Archive Snyk Scan Results
#       uses: actions/upload-artifact@v2
#       with:
#           name: Archive Snyk Open Source Scan Results
#           path: | 
#             results_iac.sarif
#             results_iac.html  
#     - name: Upload SARIF file
#       uses: github/codeql-action/upload-sarif@v2
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: results_iac.sarif
        
